-- =========================================================
-- Personal VRChat Site / Supabase Setup
-- 在 Supabase Dashboard -> SQL Editor 中整段执行
-- =========================================================

create table if not exists public.site_profile (
    id bigint primary key default 1,
    display_name text,
    tagline text,
    introduction text,
    avatar_url text,
    active_title text,
    inactive_title text
);

create table if not exists public.site_appearance (
    id bigint primary key default 1,
    background_type text default 'default',
    solid_color text default '#6d5dfc',
    gradient_start text default '#667eea',
    gradient_end text default '#764ba2',
    gradient_direction text default '135deg',
    background_image_url text,
    background_blur integer default 0,
    background_brightness integer default 100
);

create table if not exists public.info_cards (
    id bigint generated by default as identity primary key,
    title text not null default 'Untitled',
    content text default '',
    position text not null default 'center'
        check (position in ('left','center','right')),
    display_style text not null default 'normal'
        check (display_style in ('normal','connected')),
    group_id text,
    sort_order integer default 0
);

create table if not exists public.visitor_sessions (
    visitor_id text primary key,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

insert into public.site_profile (id, display_name, tagline, introduction, active_title, inactive_title)
values (
    1,
    'Your Name',
    'Welcome to my personal space.',
    '这里以后可以填写你的自我介绍。',
    'Ciallo～(∠・ω< )⌒★',
    '|´•ω•`)…'
)
on conflict (id) do nothing;

insert into public.site_appearance (id)
values (1)
on conflict (id) do nothing;

alter table public.site_profile enable row level security;
alter table public.site_appearance enable row level security;
alter table public.info_cards enable row level security;
alter table public.visitor_sessions enable row level security;

-- 可公开读取主页数据
drop policy if exists "public read profile" on public.site_profile;
create policy "public read profile"
on public.site_profile for select
using (true);

drop policy if exists "public read appearance" on public.site_appearance;
create policy "public read appearance"
on public.site_appearance for select
using (true);

drop policy if exists "public read cards" on public.info_cards;
create policy "public read cards"
on public.info_cards for select
using (true);

-- 已登录的 Supabase Auth 用户可以修改网站内容
drop policy if exists "authenticated manage profile" on public.site_profile;
create policy "authenticated manage profile"
on public.site_profile for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated manage appearance" on public.site_appearance;
create policy "authenticated manage appearance"
on public.site_appearance for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated manage cards" on public.info_cards;
create policy "authenticated manage cards"
on public.info_cards for all to authenticated
using (true) with check (true);

-- 访客统计：允许匿名读、插入、更新自己的 visitor_id。
-- 这是静态 GitHub Pages 下的基础方案，不适合作为严格防刷统计。
drop policy if exists "public read visitors" on public.visitor_sessions;
create policy "public read visitors"
on public.visitor_sessions for select
using (true);

drop policy if exists "public insert visitors" on public.visitor_sessions;
create policy "public insert visitors"
on public.visitor_sessions for insert
with check (true);

drop policy if exists "public update visitors" on public.visitor_sessions;
create policy "public update visitors"
on public.visitor_sessions for update
using (true) with check (true);

-- 图片存储桶
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'site-images',
    'site-images',
    true,
    10485760,
    array['image/jpeg','image/png','image/webp','image/gif','image/avif']
)
on conflict (id) do update
set public = true,
    file_size_limit = 10485760;

drop policy if exists "public read site images" on storage.objects;
create policy "public read site images"
on storage.objects for select
using (bucket_id = 'site-images');

drop policy if exists "authenticated upload site images" on storage.objects;
create policy "authenticated upload site images"
on storage.objects for insert to authenticated
with check (bucket_id = 'site-images');

drop policy if exists "authenticated update site images" on storage.objects;
create policy "authenticated update site images"
on storage.objects for update to authenticated
using (bucket_id = 'site-images')
with check (bucket_id = 'site-images');

drop policy if exists "authenticated delete site images" on storage.objects;
create policy "authenticated delete site images"
on storage.objects for delete to authenticated
using (bucket_id = 'site-images');

-- =========================================================
-- 执行完以后：
-- 1. Authentication -> Users -> Add user，创建你的管理员邮箱/密码
-- 2. 打开 https://你的GitHubPages地址/admin.html
-- 3. 使用该邮箱和密码登录
-- =========================================================
